version: "3.7"

networks:
    lcms-network:
        driver: bridge

services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: my_custom_l8_image
        container_name: lcms
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./:/var/www
        networks: 
            - lcms-network
    
    mysql:
        image: mysql:5.7.33
        container_name: lcms_db
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: lcms
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: laravel8
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks:
            - lcms-network
    
    nginx:
      image: nginx:alpine
      container_name: lcms_server
      restart: unless-stopped
      tty: true
      ports: 
          - 8000:80
      volumes: 
          - ./:/var/www
          - ./nginx/conf:/etc/nginx/conf.d
      networks: 
          - lcms-network